# Gradle JVM arguments.
# For more information, try 'gradle --help'
# org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# When configured, Gradle will run in incubating parallel mode.
# org.gradle.parallel=true

# When configured, Gradle builds a more extensive model of your project that allows
# IDEs to provide more specific guidance.
# org.gradle.configureondemand=false

# AndroidX specific properties
android.useAndroidX=true
android.enableJetifier=true
